// <auto-generated />
using System;
using HumanResource.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResource.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("HumanResource.Api.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.EducationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DegreeType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsDayDivision")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsGraduated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<string>("Minor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("EducationRecords");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relation")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AboriginalStatus")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgreedToTerms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowContactCurrentEmployer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmyBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmyClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmyOtherReason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ArmyPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ArmyPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmyType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Autobiography")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChineseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhoneArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhoneExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityRank")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomesticTravelPlace")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DomesticTravelWilling")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EarliestStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone1Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone1Ext")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone1Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone2Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone2Ext")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone2Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyRelation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedMonthlySalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedYearlySalary")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FormDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuturePlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhoneArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhoneExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeZipCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interests")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingZipCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverseasTravelPlace")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverseasTravelWilling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecruitPosition")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SalaryByCompanyRule")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SalaryNegotiable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMemo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.LanguageSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListeningLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingLevel")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeakingLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("WritingLevel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("LanguageSkills");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.ReferenceContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhoneArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhoneExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relation")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ReferenceContacts");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChineseName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndustryType")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsVoluntaryLeave")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlySalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearlySalary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.Certificate", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("Certificates")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.EducationRecord", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("Educations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.FamilyMember", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.JobApplication", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.User", "User")
                        .WithOne("Application")
                        .HasForeignKey("HumanResource.Api.Entities.JobApplication", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.LanguageSkill", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("Languages")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.ReferenceContact", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("References")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.UserSession", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.WorkExperience", b =>
                {
                    b.HasOne("HumanResource.Api.Entities.JobApplication", "Application")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.JobApplication", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Languages");

                    b.Navigation("References");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("HumanResource.Api.Entities.User", b =>
                {
                    b.Navigation("Application");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
